name: Generate Snake Animation

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight daily
  workflow_dispatch: # Allows manual execution

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from Contribution Grid
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: the-abhishekroy
          outputs: |
            dist/snake.svg?palette=github-dark

      - name: Push Generated Files to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
